---
version: '2'
services:
  olfs:
    build: ./olfs
    env_file: ${PWD}/local.env
    image: olfs:latest
    ports:
     - "8080:8080"
    links:
     - besd
  #  tty: true
  #  volumes:
  #   - /var/log/opendap/nginx:/var/log/nginx/
  #   - /var/log/opendap/tomcat:/var/log/tomcat/
  besd:
    build: ./besd
    env_file: ${PWD}/local.env
    image: besd:latest
  #  volumes:
  #   - /ftp:/ftp:ro
  #   - /share:/share:ro
  #   - /share/apps/opendap/DATASETS:/usr/local/share/hyrax/DATASETS:ro
  #   - /var/log/opendap/bes:/var/log/bes/
