#!/bin/bash
###############################################################################################
# 
# Make a docker distribution for a given Hyrax release.
#
#
# Some shell state reference:
# set -f # "set -o noglob"  Disable file name generation using metacharacters (globbing).
# set -v # "set -o verbose" Prints shell input lines as they are read.
# set -x # "set -o xtrace"  Print command traces before executing command.
# set -e #  Exit on error.
#
# In general use "set -e" when running commands that matter and don't use
# it for debugging stuff.
#
# Set one or more individual labels

set -e # exit on error
set -x # show what's happening

HYRAX_MAJOR_VERSION="1.15"
HYRAX_FULL_VERSION="1.15.3"
OLFS_VERSION="1.18.3"
LIBDAP_VERSION="3.20.3-1"
BES_VERSION="3.20.3-1"
RELEASE_DATE="2019-02-25"

DOCKER_RELEASE="hyrax-${HYRAX_FULL_VERSION}";


containers="besd olfs ncWMS hyrax"


mkdir -p "${DOCKER_RELEASE}"
cp -R template/* "${DOCKER_RELEASE}"

for docker_container in ${containers}
do
    cat template/${docker_container}/Dockerfile | \
    sed -e "s/HYRAX_MAJOR_VERSION_TEMPLATE/${HYRAX_MAJOR_VERSION}/g" \
        -e "s/HYRAX_FULL_VERSION_TEMPLATE/${HYRAX_FULL_VERSION}/g" \
        -e "s/OLFS_VERSION_TEMPLATE/${OLFS_VERSION}/g" \
        -e "s/BES_VERSION_TEMPLATE/${BES_VERSION}/g" \
        -e "s/LIBDAP_VERSION_TEMPLATE/${LIBDAP_VERSION}/g" \
        -e "s/RELEASE_DATE_TEMPLATE/${RELEASE_DATE}/g"  \
        > ${DOCKER_RELEASE}/$docker_container/Dockerfile  
done

cd ${DOCKER_RELEASE}
for docker_container in ${containers}
do
    docker build -t `echo "${docker_container}" | tr '[:upper:]' '[:lower:]'` ${docker_container};
done

cd ..





