---
version: '3'
services:
  olfs:
    build: ./olfs
    env_file: ${PWD}/local.env
    image: olfs:latest
    ports:
     - "8080:8080"
    tty: true
    volumes:
     - ./logs/olfs_tomcat:/usr/local/tomcat/logs
     - ./logs:/usr/local/tomcat/webapps/opendap/WEB-INF/conf/logs
  besd:
    build: ./besd
    env_file: ${PWD}/local.env
    image: besd:latest
    ports:
     - "10022:10022"
    volumes:
      - ./logs:/var/log/bes/
    # command: -e admin_contact@email.org -s
