#!/bin/bash

uid="${1:-""}"
pwrd="${2:-""}"

no_cache=
if test -n "$3"
then
    no_cache="--no-cache"
fi
echo "no_cache: $no_cache"

sudo docker build $no_cache \
    --platform "linux/amd64,linux/arm64" \
    --tag "opendap/rocky9_hyrax_builder:latest" \
    rocky9_hyrax_builder

if test -n "$uid" && test -n "$pwrd"
then
    repo="docker.io"
    echo "Pushing image to: $repo"
    docker login -u "$uid" -p "$pwrd" "$repo"
    docker push opendap/rocky9_hyrax_builder:latest
fi