#!/bin/bash

uid="${1:-""}"
pwrd="${2:-""}"

no_cache=
if test -n "$3"
then
    no_cache="--no_cache"
fi
echo "no_cache: $no_cache"

sudo docker build $no_cache \
    --platform "linux/amd64,linux/arm64" \
    --tag "opendap/rocky9_hyrax_builder:latest" \
    build-rhel9

docker login -u "$uid" -p "$pwrd" docker.io
docker push opendap/rocky9_hyrax_builder:latest
