#!/bin/bash
HR="#######################################################################"
###########################################################################
# loggy()
function loggy(){
    echo  "$@" | awk '{ print "# "$0;}'  >&2
}

###########################################################################
# Remove all containers
function drmac(){
    docker rm -f $(docker ps -aq);
}

###########################################################################
# Remove all images
function drmai(){
    docker rmi -f $(docker images -q);
}



###########################################################################
# use_branch()
function use_branch() {
    local prolog="use_branch() -"
    loggy "$prolog BEGIN"

    local repo="${1}"
    loggy "$prolog repo: $repo"

    local branch="${2}"
    loggy "$prolog branch: $branch"

    local start_dir
    start_dir="$PWD"

    cd "$repo"
    loggy "$prolog Fetching and checking out target branch $branch in: $PWD"
    git remote set-branches origin '*'
    git fetch -v --depth=1
    git checkout "$branch"
    status=$?
    if test $status -ne 0
    then
        loggy "ERROR! Failed to checkout branch '$branch' for repository: '$repo'"
        cd "$start_dir"
        return $status
    fi

    cd "$start_dir"
    loggy "$prolog END (pwd: $PWD)"
}

###########################################################################
# clean_and_get_repo()
function clean_and_get_repo() {
    local prolog="clean_and_get_repo() -"
    local repo_name="$1"
    local branch_name="$2"
    local host_target="$3"

    # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    # cleanup repo from previous efforts
    loggy "$prolog Cleaning $host_target"
    loggy "$prolog Removed $( rm -vrf $host_target | wc -l ) files."

    # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    # Clone fresh repo
    local repo_url
    repo_url="https://github.com/OPENDAP/$repo_name"
    loggy "$prolog Cloning $repo_url"
    git clone --depth 1 "$repo_url" "$host_target"

    if test -n "$branch_name"
    then
        use_branch "$host_target" "$branch_name"
    fi
}

###########################################################################
# build_libdap_for_rh8
function build_libdap_for_ubuntu() {
    prolog="build_libdap_for_rh8() -"
    local branch_name="$1"
    local clean="$2"

    # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    # configuration

    local repo_name="libdap4"
    loggy "$prolog Using repo_name: $repo_name"

    local host_target
    host_target="$(pwd)/libdap4"
    loggy "$prolog Using host_target: $host_target"

    local rpmdir
    rpmdir="$(pwd)/rpmdir"
    loggy "$prolog Using rpmdir: $rpmdir"
    mkdir -p "$rpmdir"

    local BUILD_NUMBER="666"
    loggy "$prolog BUILD_NUMBER: $BUILD_NUMBER"

    local image="opendap/ubuntu_hyrax_builder:latest"
    loggy "$prolog Using Docker Image: $image"

    local build_script="/root/libdap4/travis/build-rh8-rpm.sh"
    loggy "$prolog build_script (inside docker image): $build_script"

    if test -n "$clean"
    then
        clean_and_get_repo "$repo_name" "$branch_name" "$host_target"
    fi

    # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    # Build it
    loggy "$prolog Starting docker. Image: $image"
    docker run -it \
        --volume "$host_target":/root/libdap4 \
        --volume "$rpmdir":/root/rpmbuild \
        --env os=rocky8 \
        --env prefix="/root/install" \
        --env LIBDAP_BUILD_NUMBER=$BUILD_NUMBER \
        $image \
        $build_script
}
###########################################################################
# build_hyrax_dependencies_for_rh8
function build_hyrax_dependencies_for_ubuntu() {
    local prolog="build_hyrax_dependencies_for_rh8() -"
    loggy "$HR"
    loggy "$prolog BEGIN"
    local branch_name="$1"
    loggy "$prolog branch_name: $branch_name"

    local clean="$2"
    loggy "$prolog clean=$clean"

    local interactive="$3"
    loggy "$prolog interactive: $interactive"
    # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    # configuration

    local repo_name="hyrax-dependencies"
    loggy "$prolog Using repo_name: $repo_name"

    local top_dir
    top_dir="$PWD"

    local host_target
    host_target="$top_dir/$repo_name"
    loggy "$prolog Using host_target: $host_target"

    local host_result_dir
    host_result_dir="$top_dir/install"
    loggy "$prolog Using host_result_dir: $host_result_dir"
    mkdir -vp "$host_result_dir"

    local result_bundle="$host_target/package/hyrax-dependencies-ubuntu.tar.gz"
    loggy "$prolog Using result_bundle: $result_bundle"


    local docker_target="/root/$repo_name"
    loggy "$prolog Using docker_target: $docker_target"

    local docker_result_dir="/root/install"
    loggy "$prolog Using docker_result_dir: $docker_result_dir"

    local image="opendap/ubuntu_hyrax_builder:latest"
    loggy "$prolog Using Docker Image: $image"

    local build_script=""
    if test -z "$interactive"
    then
        build_script="-c \"make -j16 for-travis\" "
        loggy "$prolog build_script (inside docker image): '$build_script'"
    else
        loggy "$prolog This is an interactive deployment, no build script used."
    fi

    if test -n "$clean"
    then
        clean_and_get_repo "$repo_name" "$branch_name" "$host_target"
    fi

    # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    # Build it
    loggy "$prolog Starting docker. Image: $image"
    docker run -it \
        --volume "$host_target":"$docker_target" \
        --volume "$host_result_dir":"$docker_result_dir" \
        --env extra_targets="aws_s2n_tls" \
        --env prefix="$docker_result_dir" \
        --env BUILD_NUMBER=666 \
        $image $build_script
    status=$?
    if test $status -ne 0
    then
        loggy "$prolog ERROR! Docker run command failed! status: $status"
        return $status;
    fi

    loggy "$prolog Packaging results. result_bundle: $result_bundle"
    mkdir -p $host_target/package
    tar -C $top_dir -czvf $result_bundle install
    loggy "$prolog "
    loggy "$prolog Produced dependencies tar file: "
    loggy "$(ls -l $result_bundle)"
    loggy "$prolog "
    loggy "$prolog Inventory: "
    loggy "$(tar -tf $result_bundle)"
    loggy "$prolog"
    loggy "$prolog END"
}


# build_libdap_for_rh8 "" ""
# build_hyrax_dependencies_for_rh8 RHEL9 c

