#!/bin/bash

###########################################################################
# loggy()
function loggy(){
    echo  "$@" | awk '{ print "# "$0;}'  >&2
}


###########################################################################
# configuration

export start_dir="$PWD"

export target
target="$(pwd)/libdap4"
loggy "Using target: $target"

export BUILD_NUMBER="666"
loggy "BUILD_NUMBER: $BUILD_NUMBER"

# export image="opendap/rocky9_hyrax_builder:latest"
export image="localhost/opendap/rh9-build-platform:latest"
loggy "image: $image"

export libdap_build_script="/root/libdap4/travis/build-rpm-9.sh"
loggy "libdap_build_script (inside docker image): $libdap_build_script"

###########################################################################
# cleanup previous
loggy "Cleaning $target"
loggy "$(rm -vrf $target)"

###########################################################################
# Clone freshy
libdap4_repo="https://github.com/OPENDAP/libdap4"
loggy "Cloning $libdap4_repo"
git clone --depth 1 "$libdap4_repo" "$target"
# git clone "$libdap4_repo" "$target"
cd "$target"
echo "Fetching and checking out target branch in: $PWD"
git remote set-branches origin '*'
git fetch -v --depth=1
git checkout RHEL9
cd "$start_dir"
echo "pwd: $PWD"

###########################################################################
# rpm time...
mkdir -p "$target/rpmbuild"

###########################################################################
# Build it
loggy "Starting docker. Image: $image"
docker run -it \
    --volume "$target":/root/libdap4 \
    --env PREFIX="/root/install" \
    --env prefix="/root/install" \
    --env os=rocky9 \
    --env LIBDAP_BUILD_NUMBER=$BUILD_NUMBER \
    --env AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID \
    --env AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY \
    $image

    #$libdap_build_script



