#!/bin/bash
#############################################################################
# test_hyrax_service_version
#
# Travis invocation:
#
#    - $TRAVIS_BUILD_DIR/travis/test_hyrax_service_version  \
#             "http://localhost:8080/opendap" \
#             "$HYRAX_WEB_UI_VERSION"
#
# This script tests a running Hyrax service to see if various HTTP responses
# contain the expected version information.
#
# !! NOTE !!
# As written this script  leaves the docker container running so that downstream
# service tests can be easily run.
#

HR0="#######################################################################"
HR1="- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -"
HR2="--- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---"
#############################################################################
# loggy()
function loggy() {
    echo "$@" | awk '{ print "# "$0;}' >&2
}


#############################################################################
# test_response_content()
# Test one of the contents.html responses (dynamic) for the presence of the
# expected_hyrax_version string
function test_response_content(){
    local prolog="test_response_content() -"
    loggy "$HR1"
    loggy "$prolog BEGIN"

    local test_url="$1"
    if test -z "$test_url"; then
        loggy "$prolog ERROR! You must pass a test url string as parameter 1"
        return 1
    fi

    local expected_string="$2"
    if test -z "$expected_string"; then
        loggy "$prolog ERROR! You must pass an expected string as parameter 2"
        return 2
    fi

    local status
    local some_page

    #####################################################################
    # Check contents.html
    #
    loggy "$prolog Checking '$test_url' for correct the expected string: '$expected_string'"
    some_page="$(curl -s -c cookies -b cookies -n "$NETRC_FILE" -L "$test_url")"
    # loggy "$prolog $contents_url: "
    # loggy "$some_page"
    echo "$some_page" | grep "$expected_string"
    status=$?
    if test $status -ne 0
    then
        loggy "$prolog ERROR! The expected string: '$expected_string' was not found in the '$test_url' page."
        return  $status
    else
        loggy "$prolog SUCCESS!  The test url: '$test_url' response contained the expected string: '$expected_string'"
    fi
    loggy "$prolog END"
    return 0
}

#############################################################################
# test_hyrax_version_response()
# Test the Hyrax version response document for the
# expected version string.
function test_hyrax_version_response(){
    local prolog="test_hyrax_version_response() -"
    loggy "$HR1"
    loggy "$prolog BEGIN"

    local end_point_url="$1"
    loggy "$prolog         end_point_url: $end_point_url"

    local expected_version_str="$2"
    loggy "$prolog  expected_version_str: $expected_version_str"

    local version_url="$end_point_url/hyrax/version"
    loggy "$prolog           version_url: $version_url"

    local version_response_str="<Hyrax version=\"$expected_hyrax_version\""
    test_response_content   "$version_url" "$version_response_str"

    loggy "$prolog END"
    loggy "$HR1"
    return 0
}


#########################################################################################################
# test_HyraxVersion_class_endpoints()
#     Verify that we have the expected server version
function test_version_from_hyrax_service_endpoints() {
    local prolog="test_HyraxVersion_class_endpoints() -"
    loggy "$HR0"
    loggy "$prolog BEGIN"

    local end_point_url="$1"
    if test -z "$end_point_url"; then
        loggy "$prolog ERROR! You must pass a Hyrax endpoint url string as parameter 1"
        return 1
    fi
    loggy "$prolog end_point_url: $end_point_url"

    local expected_hyrax_version="$2"
    if test -z "$expected_hyrax_version"; then
        loggy "$prolog ERROR! You must pass a Hyrax endpoint url string as parameter 2"
        return 2
    fi
    loggy "$prolog expected_hyrax_version: $expected_hyrax_version"


    #####################################################################
    # Check The Hyrax Version Response
    #
    loggy "$prolog Checking a Hyrax version response page for the expected version string."

    local version_url="$end_point_url/hyrax/version"
    loggy "$prolog           version_url: $version_url"

    local version_response_str="<Hyrax version=\"$expected_hyrax_version\""
    loggy "$prolog  version_response_str: $version_response_str"

    test_response_content   "$version_url" "$version_response_str"


    #####################################################################
    # Check contents.html
    #
    loggy "$prolog Checking a contents.html page for the expected version string."

    local contents_url="$end_point_url/hyrax/contents.html"
    loggy "$prolog Using contents_url: $contents_url"

    test_response_content "$contents_url" "$expected_hyrax_version"


    #####################################################################
    # Check DAP4 Data Request Form
    #
    loggy "$HR1"
    loggy "$prolog Checking DAP4 Data Request Form page for correct version."

    local ifh_url="$end_point_url/hyrax/data/nc/fnoc1.nc.dmr.html"
    loggy "$prolog Using ifh_url: $ifh_url"

    test_response_content "$ifh_url" "$expected_hyrax_version"

    loggy "$prolog END"
    loggy "$HR0"
    return 0
}


#########################################################################################################
#########################################################################################################
#########################################################################################################
#########################################################################################################


#############################################################################
# Processing Command Line Options (Inline Execution)
#

prolog="test_hyrax_service_version[] -"

end_point_url="$1"
if test -z "$end_point_url"; then
    loggy "$prolog ERROR! You must pass a Hyrax endpoint url string as parameter 1"
    return 1
fi

expected_hyrax_version="$2"
if test -z "$expected_hyrax_version"; then
    loggy "$prolog ERROR! You must pass a Hyrax endpoint url string as parameter 2"
    return 2
fi

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    # Run the script invoked as an application,
    loggy "$HR0"
    loggy "$prolog BEGIN"

    set -e
    test_version_from_hyrax_service_endpoints  "$end_point_url" "$expected_hyrax_version"

    loggy "$prolog END"
    loggy "$HR0"
else
    # Otherwise...
    # Just source it into the current shell.
    loggy "$prolog SUCCESS! The test_hyrax_service_version functions have been loaded in to the current shell."
fi


