#!/bin/bash

HR0="#######################################################################"
HR1="- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -"
HR2="--- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---"
#############################################################################
# loggy()
function loggy() {
    echo "$@" | awk '{ print "# "$0;}' >&2
}

#########################################################################################################
# test_docker_image_label()
#     Looks at the metadata of docker image 'd_id' ($1) using docker 'inspect'
#     to retrieve the value of 'label_key' ($2) from the docker .Config.Labels
#     The retrieved value is compared with the 'expected_value' ($3)
#
function test_docker_image_label() {
    local prolog="test_docker_image_label() -"
    loggy "$HR2"
    loggy "$prolog BEGIN"

    local d_id="$1"
    local label_key="$2"
    local expected_value="$3"

    local docker_labels
    local status

    loggy "$prolog Retrieving docker image metadata for correct Hyrax version..."
    docker_labels="$(docker inspect --format="{{ index .Config.Labels}}" "$d_id")"
    loggy "$prolog docker_labels:"
    loggy "$docker_labels"
    loggy ""

    loggy "$prolog Checking the value of label '$label_key' from docker image '$d_id' metadata..."
    key_value="$(docker inspect --format="{{ index .Config.Labels \"$label_key\" }}" "$d_id")"
    loggy "key_value: '$key_value'"
    if test "$expected_value" = "$key_value"; then
        loggy "$prolog SUCCESS!
        The 'docker inspect' command for $d_id returned the expected_value string."
    else
        loggy "$prolog ERROR!
        The value of the the docker label '$label_key' found in the docker
        inspect response does not match the expected_value '$expected_value'
        in this production environment!"
        return 1
    fi

    loggy "$prolog END"
    loggy "$HR2"
    return 0
}


#########################################################################################################
# test_file_in_docker_image()
#     Looks inside docker image 'd_id' ($1) in the file
#     named file_path ($2) for the string 'expected_value' ($3)
#
function test_file_in_docker_image() {
    local prolog="test_file_in_docker_image() -"
    loggy "$HR2"
    loggy "$prolog BEGIN"

    local d_id="$1"
    local file_path="$2"
    local expected_value="$3"

    local status
    local some_file

    loggy "$prolog Checking for '$expected_value' in '$d_id::$file_path'"
    some_file="$(docker run --rm --entrypoint cat "$d_id" "$file_path")"

    # loggy "$prolog $d_id::$file_path: "
    # loggy "$some_file"
    echo "$some_file" | grep "$expected_value"
    status=$?
    if test $status -ne 0; then
        loggy "$prolog ERROR! The expected value '$expected_value' was not found in the file '$file_path'"
        loggy "$prolog $d_id::$file_path: "
        loggy "$some_file"
        return $status
    else
        loggy "$prolog SUCCESS! Found it!"
    fi
    loggy "$prolog END"
    loggy "$HR2"
    return 0
}
#docker cp $CONTAINER_ID:/path/in/container /path/on/host


#########################################################################################################
# get_docker_label_version_key()
#   Returns the purported  Docker .Config.Labels entry for the current application build.
#   Relies on the global variable DOCKER_NAME and embodies some inside knowledge of the irregularities
#   In our docker labeling scheme.In particular some applications like ngap and hyrax_ncwms use
#   the "hyrax" version in their Docker labels.
function get_docker_label_version_key(){
    local prolog="get_docker_label_version_key() -"
    local app_key="$DOCKER_NAME"                             # default
    # if test -n "$DOCKER_DIR"; then app_key="$DOCKER_DIR"; fi # DOCKER_DIR if it's in use.
    if test "$app_key" = "ngap" -o "$app_key" = "hyrax_ncwms"; then app_key="hyrax"; fi   # ngap is Hyrax so....

    local label_version_key="org.opendap.$app_key.version"
    loggy "$prolog label_version_key: $label_version_key"
    echo "$label_version_key"
}


function get_expected_docker_label_version_value(){
    local prolog="get_expected_docker_label_version_value() -"
    #################################################################################################
    # Target specific tweaking using global values
    # @TODO - refactor and move upstream where possible
    local expected_version_str="$HYRAX_WEB_UI_VERSION"
    if test "$DOCKER_NAME" = "besd"; then expected_version_str="$BES_VERSION"; fi
    if test "$DOCKER_NAME" = "olfs"; then expected_version_str="$OLFS_VERSION"; fi
    loggy "$prolog   expected_version_str: $expected_version_str"
    echo "$expected_version_str"
}

#########################################################################################################
# test_docker_version_label()
#     Examine the .Config.Labels metadata in "d_id" and test that the application version for our
# application is correct.
function test_docker_version_label(){
    local prolog="test_docker_version_label() -"

    local d_id="$1"
    if test -z "$d_id"; then
        loggy "$prolog ERROR! You must pass valid docker id as parameter 1"
        return 1
    fi
    loggy "$prolog                   d_id: $d_id"

    local label_version_key
    label_version_key="$(get_docker_label_version_key)"
    loggy "$prolog      label_version_key: $label_version_key"

    local expected_version_str
    expected_version_str="$(get_expected_docker_label_version_value)"
    #################################################################
    # The check the docker image metadata (in .Config.Labels) for
    # our version information.
    test_docker_image_label "$d_id" "$label_version_key" "$expected_version_str"
    status=$?
    if test $status -ne 0; then
        loggy "$prolog ERROR! The expected version string was not found in the docker image metadata."
        return $status
    fi

}


#########################################################################################################
# test_docker_hyrax_version()
#     Examine the Hyrax deployment in "d_id" and check the value of the Hyrax version strings
# in the expected locations.
function test_docker_hyrax_versions() {
    local prolog="test_docker_hyrax_versions() -"
    loggy "$HR1"
    loggy "$prolog BEGIN"

    local d_id="$1"
    if test -z "$d_id"; then
        loggy "$prolog ERROR! You must pass valid docker id as parameter 1"
        return 1
    fi
    loggy "$prolog                   d_id: $d_id"

    local status

    # The default deployment context is "opendap" but the ngap application is deployed to "ROOT"
    local deployment_context="opendap"
    if test "$DOCKER_NAME" = "ngap"; then deployment_context="ROOT"; fi
    loggy "$prolog     deployment_context: $deployment_context"

    local expected_version_str
    expected_version_str="$(get_expected_docker_label_version_value)"
    loggy "$prolog   expected_version_str: $expected_version_str"

    #################################################################
    # The NGAP build has a static landing page that needs to match.
    if test "$DOCKER_NAME" = "ngap"; then
        test_file_in_docker_image "$d_id" "/usr/share/tomcat/webapps/$deployment_context/docs/ngap/ngap.html" "$expected_version_str"
        status=$?
        if test $status -ne 0; then
            loggy "$prolog ERROR! The expected version string was not found in the file."
            return $status
        fi
    fi

    #################################################################
    # All the service deployments (except the besd) have the OLFS
    # installed in Tomcat. We check the version.xsl static file for
    # the Hyrax version (not the OLFS version, at least in that location)
    if test "$DOCKER_NAME" != "besd"; then
        local version_xsl="/usr/share/tomcat/webapps/$deployment_context/xsl/version.xsl"
        test_file_in_docker_image "$d_id" "$version_xsl" "$HYRAX_WEB_UI_VERSION"
        status=$?
        if test $status -ne 0; then
            loggy "$prolog ERROR! The expected version string was not found in the file: '$d_id::$version_xsl'"
            return $status
        fi
    fi
    loggy "$prolog END"
    loggy "$HR1"
    return 0
}

#############################################################################
# Processing Command Line Options (Inline Execution)
#
prolog="test_docker_image_version[] -"

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    # Run the script invoked as an application,
    loggy "$HR0"
    loggy "$prolog BEGIN"

    docker_image_id="$1"
    if test -z "$docker_image_id"
    then
        loggy "ERROR! You must supply a docker id to use theis script."
        exit 1
    fi

    set -e
    test_docker_version_label "$docker_image_id"
    test_docker_hyrax_versions "$docker_image_id"

    loggy "$prolog END"
    loggy "$HR0"
else
    # Otherwise...
    # Just source it into the current shell.
    loggy "$prolog SUCCESS! The test_docker_image_version functions have been loaded in to the current shell."
fi










