#!/bin/bash

HR0="#######################################################################"
HR1="- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -"
HR2="--- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---"
#############################################################################
# loggy()
function loggy() {
    echo "$@" | awk '{ print "# "$0;}' >&2
}

function test_hyrax_version_response(){
    local prolog="test_hyrax_version_response() -"
    loggy "$HR1"
    loggy "$prolog BEGIN"

    local end_point_url="$1"
    loggy "$prolog         end_point_url: $end_point_url"

    local expected_version_str="$2"
    loggy "$prolog  expected_version_str: $expected_version_str"


    local version_url="$end_point_url/hyrax/version"
    loggy "$prolog           version_url: $end_point_url"

    #####################################################
    # Get Hyrax version response from the running server
    loggy "$prolog Retrieving Hyrax Version Response from: '$version_url'"
    version_response="$(curl -s -c cookies -b cookies -n $NETRC_FILE -L "$version_url")"
    loggy "$prolog Hyrax Version Response:"
    loggy "$version_response"
    loggy "$HR1"

    ############################################################
    # Verify Hyrax Version Injection
    #   Get this line from the version response:
    #       <Hyrax version="##########" />
    #   and then use awk to get the actual value of ##########
    local hyrax_version_value
    hyrax_version_value="$(echo "$version_response" | grep "<Hyrax version" | awk '{split($0, a, "\""); print a[2];}')"
    loggy "$prolog hyrax_version_response: $hyrax_version_value"
    loggy "$prolog expected_hyrax_version: $expected_version_str"
    if test "$expected_version_str" == "$hyrax_version_value"; then
        loggy "$prolog SUCCESS!
        The value of the Hyrax version returned in the Hyrax version response from the tested docker image matches the
        expected_hyrax_version value."
    else
        loggy "$prolog ERROR!
        The value of the hyrax version string '$hyrax_version_value' returned in the version
        response does not match the expected_hyrax_version env value '$expected_version_str'
        in this production environment!"
        return 1
    fi
    loggy "$prolog END"
    loggy "$HR1"
    return 0
}


test_hyrax_version_response $1 $2
